/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttackSimplified {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Attack start timestamp.
    #[serde(rename = "started", skip_serializing_if = "Option::is_none")]
    pub started: Option<i32>,
    /// Attack end timestamp.
    #[serde(rename = "ended", skip_serializing_if = "Option::is_none")]
    pub ended: Option<i32>,
    #[serde(rename = "attacker", skip_serializing_if = "Option::is_none")]
    pub attacker: Option<Box<models::AttackSimplifiedAttacker>>,
    #[serde(rename = "defender", skip_serializing_if = "Option::is_none")]
    pub defender: Option<Box<models::AttackPlayerSimplified>>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<models::FactionAttackResult>,
    #[serde(rename = "respect_gain", skip_serializing_if = "Option::is_none")]
    pub respect_gain: Option<f32>,
    #[serde(rename = "respect_loss", skip_serializing_if = "Option::is_none")]
    pub respect_loss: Option<f32>,
}

impl AttackSimplified {
    pub fn new() -> AttackSimplified {
        AttackSimplified {
            id: None,
            code: None,
            started: None,
            ended: None,
            attacker: None,
            defender: None,
            result: None,
            respect_gain: None,
            respect_loss: None,
        }
    }
}

