/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttackModifiers {
    #[serde(rename = "fair_fight", skip_serializing_if = "Option::is_none")]
    pub fair_fight: Option<f32>,
    #[serde(rename = "war", skip_serializing_if = "Option::is_none")]
    pub war: Option<f32>,
    #[serde(rename = "retaliation", skip_serializing_if = "Option::is_none")]
    pub retaliation: Option<f32>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<f32>,
    #[serde(rename = "overseas", skip_serializing_if = "Option::is_none")]
    pub overseas: Option<f32>,
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<f32>,
    #[serde(rename = "warlord", skip_serializing_if = "Option::is_none")]
    pub warlord: Option<f32>,
}

impl AttackModifiers {
    pub fn new() -> AttackModifiers {
        AttackModifiers {
            fair_fight: None,
            war: None,
            retaliation: None,
            group: None,
            overseas: None,
            chain: None,
            warlord: None,
        }
    }
}

