/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FactionMember : Details about a faction member.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FactionMember {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<i32>,
    #[serde(rename = "days_in_faction", skip_serializing_if = "Option::is_none")]
    pub days_in_faction: Option<i32>,
    #[serde(rename = "is_revivable", skip_serializing_if = "Option::is_none")]
    pub is_revivable: Option<bool>,
    #[serde(rename = "last_action", skip_serializing_if = "Option::is_none")]
    pub last_action: Option<Box<models::UserLastAction>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::UserStatus>>,
    #[serde(rename = "life", skip_serializing_if = "Option::is_none")]
    pub life: Option<Box<models::UserLife>>,
    #[serde(rename = "revive_setting", skip_serializing_if = "Option::is_none")]
    pub revive_setting: Option<models::ReviveSetting>,
}

impl FactionMember {
    /// Details about a faction member.
    pub fn new() -> FactionMember {
        FactionMember {
            id: None,
            name: None,
            position: None,
            level: None,
            days_in_faction: None,
            is_revivable: None,
            last_action: None,
            status: None,
            life: None,
            revive_setting: None,
        }
    }
}

