/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FactionTerritoryWarParticipant {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "score", skip_serializing_if = "Option::is_none")]
    pub score: Option<i32>,
    /// Faction's current chain.
    #[serde(rename = "chain", skip_serializing_if = "Option::is_none")]
    pub chain: Option<i32>,
    #[serde(rename = "is_aggressor", skip_serializing_if = "Option::is_none")]
    pub is_aggressor: Option<bool>,
    #[serde(rename = "playerIds", skip_serializing_if = "Option::is_none")]
    pub player_ids: Option<Vec<i32>>,
}

impl FactionTerritoryWarParticipant {
    pub fn new() -> FactionTerritoryWarParticipant {
        FactionTerritoryWarParticipant {
            id: None,
            name: None,
            score: None,
            chain: None,
            is_aggressor: None,
            player_ids: None,
        }
    }
}

