/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ForumSelectionName {
    #[serde(rename = "categories")]
    Categories,
    #[serde(rename = "lookup")]
    Lookup,
    #[serde(rename = "posts")]
    Posts,
    #[serde(rename = "thread")]
    Thread,
    #[serde(rename = "threads")]
    Threads,
    #[serde(rename = "timestamp")]
    Timestamp,

}

impl std::fmt::Display for ForumSelectionName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Categories => write!(f, "categories"),
            Self::Lookup => write!(f, "lookup"),
            Self::Posts => write!(f, "posts"),
            Self::Thread => write!(f, "thread"),
            Self::Threads => write!(f, "threads"),
            Self::Timestamp => write!(f, "timestamp"),
        }
    }
}

impl Default for ForumSelectionName {
    fn default() -> ForumSelectionName {
        Self::Categories
    }
}

