/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketSelectionName : The following selections will fallback to API v1 and may change at any time: 'pointsmarket'.
/// The following selections will fallback to API v1 and may change at any time: 'pointsmarket'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MarketSelectionName {
    #[serde(rename = "itemmarket")]
    Itemmarket,
    #[serde(rename = "lookup")]
    Lookup,
    #[serde(rename = "timestamp")]
    Timestamp,
    #[serde(rename = "pointsmarket")]
    Pointsmarket,

}

impl std::fmt::Display for MarketSelectionName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Itemmarket => write!(f, "itemmarket"),
            Self::Lookup => write!(f, "lookup"),
            Self::Timestamp => write!(f, "timestamp"),
            Self::Pointsmarket => write!(f, "pointsmarket"),
        }
    }
}

impl Default for MarketSelectionName {
    fn default() -> MarketSelectionName {
        Self::Itemmarket
    }
}

