/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsItemsItemsFound {
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<i32>,
    /// This field is being replaced with 'dump' field and will be removed on 1st January 2025.
    #[serde(rename = "trash", skip_serializing_if = "Option::is_none")]
    pub trash: Option<i32>,
    #[serde(rename = "dump", skip_serializing_if = "Option::is_none")]
    pub dump: Option<i32>,
    #[serde(rename = "easter_eggs", skip_serializing_if = "Option::is_none")]
    pub easter_eggs: Option<i32>,
}

impl PersonalStatsItemsItemsFound {
    pub fn new() -> PersonalStatsItemsItemsFound {
        PersonalStatsItemsItemsFound {
            city: None,
            trash: None,
            dump: None,
            easter_eggs: None,
        }
    }
}

