/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsCrimesV2Offenses {
    #[serde(rename = "vandalism", skip_serializing_if = "Option::is_none")]
    pub vandalism: Option<i32>,
    #[serde(rename = "fraud", skip_serializing_if = "Option::is_none")]
    pub fraud: Option<i32>,
    #[serde(rename = "theft", skip_serializing_if = "Option::is_none")]
    pub theft: Option<i32>,
    #[serde(rename = "counterfeiting", skip_serializing_if = "Option::is_none")]
    pub counterfeiting: Option<i32>,
    #[serde(rename = "illicit_services", skip_serializing_if = "Option::is_none")]
    pub illicit_services: Option<i32>,
    #[serde(rename = "cybercrime", skip_serializing_if = "Option::is_none")]
    pub cybercrime: Option<i32>,
    #[serde(rename = "extortion", skip_serializing_if = "Option::is_none")]
    pub extortion: Option<i32>,
    #[serde(rename = "illegal_production", skip_serializing_if = "Option::is_none")]
    pub illegal_production: Option<i32>,
    #[serde(rename = "organized_crimes", skip_serializing_if = "Option::is_none")]
    pub organized_crimes: Option<i32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl PersonalStatsCrimesV2Offenses {
    pub fn new() -> PersonalStatsCrimesV2Offenses {
        PersonalStatsCrimesV2Offenses {
            vandalism: None,
            fraud: None,
            theft: None,
            counterfeiting: None,
            illicit_services: None,
            cybercrime: None,
            extortion: None,
            illegal_production: None,
            organized_crimes: None,
            total: None,
        }
    }
}

