/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PersonalStatsCrimesCrimes {
    PersonalStatsCriminalOffensesV1(Box<models::PersonalStatsCriminalOffensesV1>),
    PersonalStatsCrimesV2(Box<models::PersonalStatsCrimesV2>),
}

impl Default for PersonalStatsCrimesCrimes {
    fn default() -> Self {
        Self::PersonalStatsCriminalOffensesV1(Default::default())
    }
}

