/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsCommunicationCommunicationMailsSent {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "friends", skip_serializing_if = "Option::is_none")]
    pub friends: Option<i32>,
    #[serde(rename = "faction", skip_serializing_if = "Option::is_none")]
    pub faction: Option<i32>,
    #[serde(rename = "colleagues", skip_serializing_if = "Option::is_none")]
    pub colleagues: Option<i32>,
    #[serde(rename = "spouse", skip_serializing_if = "Option::is_none")]
    pub spouse: Option<i32>,
}

impl PersonalStatsCommunicationCommunicationMailsSent {
    pub fn new() -> PersonalStatsCommunicationCommunicationMailsSent {
        PersonalStatsCommunicationCommunicationMailsSent {
            total: None,
            friends: None,
            faction: None,
            colleagues: None,
            spouse: None,
        }
    }
}

