/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsItemsItemsUsed {
    #[serde(rename = "books", skip_serializing_if = "Option::is_none")]
    pub books: Option<i32>,
    #[serde(rename = "boosters", skip_serializing_if = "Option::is_none")]
    pub boosters: Option<i32>,
    #[serde(rename = "consumables", skip_serializing_if = "Option::is_none")]
    pub consumables: Option<i32>,
    #[serde(rename = "candy", skip_serializing_if = "Option::is_none")]
    pub candy: Option<i32>,
    #[serde(rename = "alcohol", skip_serializing_if = "Option::is_none")]
    pub alcohol: Option<i32>,
    /// This field is being replaced with 'energy_drinks' field and will be removed on 1st January 2025.
    #[serde(rename = "energy", skip_serializing_if = "Option::is_none")]
    pub energy: Option<i32>,
    #[serde(rename = "energy_drinks", skip_serializing_if = "Option::is_none")]
    pub energy_drinks: Option<i32>,
    #[serde(rename = "stat_enhancers", skip_serializing_if = "Option::is_none")]
    pub stat_enhancers: Option<i32>,
    #[serde(rename = "easter_eggs", skip_serializing_if = "Option::is_none")]
    pub easter_eggs: Option<i32>,
}

impl PersonalStatsItemsItemsUsed {
    pub fn new() -> PersonalStatsItemsItemsUsed {
        PersonalStatsItemsItemsUsed {
            books: None,
            boosters: None,
            consumables: None,
            candy: None,
            alcohol: None,
            energy: None,
            energy_drinks: None,
            stat_enhancers: None,
            easter_eggs: None,
        }
    }
}

