/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PersonalStatsCriminalOffensesCriminalOffenses : This object is being replaced with 'crimes' object (PersonalStatsCrimes) and will be removed on 1st January 2025. Response for PersonalStatsCriminalOffenses depends on which crime version user is currently.
/// This object is being replaced with 'crimes' object (PersonalStatsCrimes) and will be removed on 1st January 2025. Response for PersonalStatsCriminalOffenses depends on which crime version user is currently.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PersonalStatsCriminalOffensesCriminalOffenses {
    PersonalStatsCriminalOffensesV1(Box<models::PersonalStatsCriminalOffensesV1>),
    PersonalStatsCriminalOffensesV2(Box<models::PersonalStatsCriminalOffensesV2>),
}

impl Default for PersonalStatsCriminalOffensesCriminalOffenses {
    fn default() -> Self {
        Self::PersonalStatsCriminalOffensesV1(Default::default())
    }
}

