/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PersonalStatsStatName : Important! Value 'hunting' is deprecated, and will be removed on 1st of January 2025.
/// Important! Value 'hunting' is deprecated, and will be removed on 1st of January 2025.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PersonalStatsStatName {
    #[serde(rename = "attackswon")]
    Attackswon,
    #[serde(rename = "attackslost")]
    Attackslost,
    #[serde(rename = "attacksdraw")]
    Attacksdraw,
    #[serde(rename = "attacksassisted")]
    Attacksassisted,
    #[serde(rename = "defendswon")]
    Defendswon,
    #[serde(rename = "defendslost")]
    Defendslost,
    #[serde(rename = "defendsstalemated")]
    Defendsstalemated,
    #[serde(rename = "elo")]
    Elo,
    #[serde(rename = "yourunaway")]
    Yourunaway,
    #[serde(rename = "theyrunaway")]
    Theyrunaway,
    #[serde(rename = "unarmoredwon")]
    Unarmoredwon,
    #[serde(rename = "bestkillstreak")]
    Bestkillstreak,
    #[serde(rename = "attackhits")]
    Attackhits,
    #[serde(rename = "attackmisses")]
    Attackmisses,
    #[serde(rename = "attackdamage")]
    Attackdamage,
    #[serde(rename = "bestdamage")]
    Bestdamage,
    #[serde(rename = "onehitkills")]
    Onehitkills,
    #[serde(rename = "attackcriticalhits")]
    Attackcriticalhits,
    #[serde(rename = "roundsfired")]
    Roundsfired,
    #[serde(rename = "specialammoused")]
    Specialammoused,
    #[serde(rename = "hollowammoused")]
    Hollowammoused,
    #[serde(rename = "tracerammoused")]
    Tracerammoused,
    #[serde(rename = "piercingammoused")]
    Piercingammoused,
    #[serde(rename = "incendiaryammoused")]
    Incendiaryammoused,
    #[serde(rename = "attacksstealthed")]
    Attacksstealthed,
    #[serde(rename = "retals")]
    Retals,
    #[serde(rename = "moneymugged")]
    Moneymugged,
    #[serde(rename = "largestmug")]
    Largestmug,
    #[serde(rename = "itemslooted")]
    Itemslooted,
    #[serde(rename = "highestbeaten")]
    Highestbeaten,
    #[serde(rename = "respectforfaction")]
    Respectforfaction,
    #[serde(rename = "rankedwarhits")]
    Rankedwarhits,
    #[serde(rename = "raidhits")]
    Raidhits,
    #[serde(rename = "territoryjoins")]
    Territoryjoins,
    #[serde(rename = "territoryclears")]
    Territoryclears,
    #[serde(rename = "territorytime")]
    Territorytime,
    #[serde(rename = "jobpointsused")]
    Jobpointsused,
    #[serde(rename = "trainsreceived")]
    Trainsreceived,
    #[serde(rename = "marketitemsbought")]
    Marketitemsbought,
    #[serde(rename = "auctionswon")]
    Auctionswon,
    #[serde(rename = "auctionsells")]
    Auctionsells,
    #[serde(rename = "itemssent")]
    Itemssent,
    #[serde(rename = "trades")]
    Trades,
    #[serde(rename = "cityitemsbought")]
    Cityitemsbought,
    #[serde(rename = "pointsbought")]
    Pointsbought,
    #[serde(rename = "pointssold")]
    Pointssold,
    #[serde(rename = "bazaarcustomers")]
    Bazaarcustomers,
    #[serde(rename = "bazaarsales")]
    Bazaarsales,
    #[serde(rename = "bazaarprofit")]
    Bazaarprofit,
    #[serde(rename = "jailed")]
    Jailed,
    #[serde(rename = "peoplebusted")]
    Peoplebusted,
    #[serde(rename = "failedbusts")]
    Failedbusts,
    #[serde(rename = "peoplebought")]
    Peoplebought,
    #[serde(rename = "peopleboughtspent")]
    Peopleboughtspent,
    #[serde(rename = "hospital")]
    Hospital,
    #[serde(rename = "medicalitemsused")]
    Medicalitemsused,
    #[serde(rename = "bloodwithdrawn")]
    Bloodwithdrawn,
    #[serde(rename = "reviveskill")]
    Reviveskill,
    #[serde(rename = "revives")]
    Revives,
    #[serde(rename = "revivesreceived")]
    Revivesreceived,
    #[serde(rename = "heavyhits")]
    Heavyhits,
    #[serde(rename = "machinehits")]
    Machinehits,
    #[serde(rename = "riflehits")]
    Riflehits,
    #[serde(rename = "smghits")]
    Smghits,
    #[serde(rename = "shotgunhits")]
    Shotgunhits,
    #[serde(rename = "pistolhits")]
    Pistolhits,
    #[serde(rename = "temphits")]
    Temphits,
    #[serde(rename = "piercinghits")]
    Piercinghits,
    #[serde(rename = "slashinghits")]
    Slashinghits,
    #[serde(rename = "clubbinghits")]
    Clubbinghits,
    #[serde(rename = "mechanicalhits")]
    Mechanicalhits,
    #[serde(rename = "h2hhits")]
    H2hhits,
    #[serde(rename = "mailssent")]
    Mailssent,
    #[serde(rename = "friendmailssent")]
    Friendmailssent,
    #[serde(rename = "factionmailssent")]
    Factionmailssent,
    #[serde(rename = "companymailssent")]
    Companymailssent,
    #[serde(rename = "spousemailssent")]
    Spousemailssent,
    #[serde(rename = "classifiedadsplaced")]
    Classifiedadsplaced,
    #[serde(rename = "personalsplaced")]
    Personalsplaced,
    #[serde(rename = "criminaloffensesold")]
    Criminaloffensesold,
    #[serde(rename = "sellillegalgoods")]
    Sellillegalgoods,
    #[serde(rename = "theftold")]
    Theftold,
    #[serde(rename = "autotheftcrime")]
    Autotheftcrime,
    #[serde(rename = "drugdealscrime")]
    Drugdealscrime,
    #[serde(rename = "computercrime")]
    Computercrime,
    #[serde(rename = "fraudold")]
    Fraudold,
    #[serde(rename = "murdercrime")]
    Murdercrime,
    #[serde(rename = "othercrime")]
    Othercrime,
    #[serde(rename = "organizedcrimes")]
    Organizedcrimes,
    #[serde(rename = "bountiesplaced")]
    Bountiesplaced,
    #[serde(rename = "totalbountyspent")]
    Totalbountyspent,
    #[serde(rename = "bountiescollected")]
    Bountiescollected,
    #[serde(rename = "totalbountyreward")]
    Totalbountyreward,
    #[serde(rename = "bountiesreceived")]
    Bountiesreceived,
    #[serde(rename = "receivedbountyvalue")]
    Receivedbountyvalue,
    #[serde(rename = "cityfinds")]
    Cityfinds,
    #[serde(rename = "dumpfinds")]
    Dumpfinds,
    #[serde(rename = "itemsdumped")]
    Itemsdumped,
    #[serde(rename = "booksread")]
    Booksread,
    #[serde(rename = "boostersused")]
    Boostersused,
    #[serde(rename = "consumablesused")]
    Consumablesused,
    #[serde(rename = "candyused")]
    Candyused,
    #[serde(rename = "alcoholused")]
    Alcoholused,
    #[serde(rename = "energydrinkused")]
    Energydrinkused,
    #[serde(rename = "statenhancersused")]
    Statenhancersused,
    #[serde(rename = "eastereggsfound")]
    Eastereggsfound,
    #[serde(rename = "eastereggsused")]
    Eastereggsused,
    #[serde(rename = "virusescoded")]
    Virusescoded,
    #[serde(rename = "traveltimes")]
    Traveltimes,
    #[serde(rename = "timespenttraveling")]
    Timespenttraveling,
    #[serde(rename = "itemsboughtabroad")]
    Itemsboughtabroad,
    #[serde(rename = "hunting")]
    Hunting,
    #[serde(rename = "attackswonabroad")]
    Attackswonabroad,
    #[serde(rename = "defendslostabroad")]
    Defendslostabroad,
    #[serde(rename = "argtravel")]
    Argtravel,
    #[serde(rename = "mextravel")]
    Mextravel,
    #[serde(rename = "uaetravel")]
    Uaetravel,
    #[serde(rename = "hawtravel")]
    Hawtravel,
    #[serde(rename = "japtravel")]
    Japtravel,
    #[serde(rename = "uktravel")]
    Uktravel,
    #[serde(rename = "satravel")]
    Satravel,
    #[serde(rename = "switravel")]
    Switravel,
    #[serde(rename = "chitravel")]
    Chitravel,
    #[serde(rename = "cantravel")]
    Cantravel,
    #[serde(rename = "caytravel")]
    Caytravel,
    #[serde(rename = "drugsused")]
    Drugsused,
    #[serde(rename = "overdosed")]
    Overdosed,
    #[serde(rename = "rehabs")]
    Rehabs,
    #[serde(rename = "rehabcost")]
    Rehabcost,
    #[serde(rename = "cantaken")]
    Cantaken,
    #[serde(rename = "exttaken")]
    Exttaken,
    #[serde(rename = "kettaken")]
    Kettaken,
    #[serde(rename = "lsdtaken")]
    Lsdtaken,
    #[serde(rename = "opitaken")]
    Opitaken,
    #[serde(rename = "pcptaken")]
    Pcptaken,
    #[serde(rename = "shrtaken")]
    Shrtaken,
    #[serde(rename = "spetaken")]
    Spetaken,
    #[serde(rename = "victaken")]
    Victaken,
    #[serde(rename = "xantaken")]
    Xantaken,
    #[serde(rename = "missionscompleted")]
    Missionscompleted,
    #[serde(rename = "contractscompleted")]
    Contractscompleted,
    #[serde(rename = "dukecontractscompleted")]
    Dukecontractscompleted,
    #[serde(rename = "missioncreditsearned")]
    Missioncreditsearned,
    #[serde(rename = "racingskill")]
    Racingskill,
    #[serde(rename = "racingpointsearned")]
    Racingpointsearned,
    #[serde(rename = "racesentered")]
    Racesentered,
    #[serde(rename = "raceswon")]
    Raceswon,
    #[serde(rename = "networth")]
    Networth,
    #[serde(rename = "timeplayed")]
    Timeplayed,
    #[serde(rename = "activestreak")]
    Activestreak,
    #[serde(rename = "bestactivestreak")]
    Bestactivestreak,
    #[serde(rename = "awards")]
    Awards,
    #[serde(rename = "refills")]
    Refills,
    #[serde(rename = "nerverefills")]
    Nerverefills,
    #[serde(rename = "tokenrefills")]
    Tokenrefills,
    #[serde(rename = "meritsbought")]
    Meritsbought,
    #[serde(rename = "daysbeendonator")]
    Daysbeendonator,
    #[serde(rename = "criminaloffenses")]
    Criminaloffenses,
    #[serde(rename = "vandalism")]
    Vandalism,
    #[serde(rename = "theft")]
    Theft,
    #[serde(rename = "counterfeiting")]
    Counterfeiting,
    #[serde(rename = "fraud")]
    Fraud,
    #[serde(rename = "illicitservices")]
    Illicitservices,
    #[serde(rename = "cybercrime")]
    Cybercrime,
    #[serde(rename = "extortion")]
    Extortion,
    #[serde(rename = "illegalproduction")]
    Illegalproduction,
    #[serde(rename = "currentkillstreak")]
    Currentkillstreak,
    #[serde(rename = "strength")]
    Strength,
    #[serde(rename = "defense")]
    Defense,
    #[serde(rename = "speed")]
    Speed,
    #[serde(rename = "dexterity")]
    Dexterity,
    #[serde(rename = "totalstats")]
    Totalstats,
    #[serde(rename = "manuallabor")]
    Manuallabor,
    #[serde(rename = "intelligence")]
    Intelligence,
    #[serde(rename = "endurance")]
    Endurance,
    #[serde(rename = "totalworkingstats")]
    Totalworkingstats,
    #[serde(rename = "moneyinvested")]
    Moneyinvested,
    #[serde(rename = "investedprofit")]
    Investedprofit,
    #[serde(rename = "investamount")]
    Investamount,
    #[serde(rename = "banktimeleft")]
    Banktimeleft,
    #[serde(rename = "stockprofits")]
    Stockprofits,
    #[serde(rename = "stocklosses")]
    Stocklosses,
    #[serde(rename = "stockfees")]
    Stockfees,
    #[serde(rename = "stocknetprofits")]
    Stocknetprofits,
    #[serde(rename = "stockpayouts")]
    Stockpayouts,
    #[serde(rename = "networthwallet")]
    Networthwallet,
    #[serde(rename = "networthvault")]
    Networthvault,
    #[serde(rename = "networthbank")]
    Networthbank,
    #[serde(rename = "networthcayman")]
    Networthcayman,
    #[serde(rename = "networthpoints")]
    Networthpoints,
    #[serde(rename = "networthitems")]
    Networthitems,
    #[serde(rename = "networthdisplaycase")]
    Networthdisplaycase,
    #[serde(rename = "networthbazaar")]
    Networthbazaar,
    #[serde(rename = "networthitemmarket")]
    Networthitemmarket,
    #[serde(rename = "networthproperties")]
    Networthproperties,
    #[serde(rename = "networthstockmarket")]
    Networthstockmarket,
    #[serde(rename = "networthauctionhouse")]
    Networthauctionhouse,
    #[serde(rename = "networthbookie")]
    Networthbookie,
    #[serde(rename = "networthcompany")]
    Networthcompany,
    #[serde(rename = "networthenlistedcars")]
    Networthenlistedcars,
    #[serde(rename = "networthpiggybank")]
    Networthpiggybank,
    #[serde(rename = "networthpending")]
    Networthpending,
    #[serde(rename = "networthloan")]
    Networthloan,
    #[serde(rename = "networthunpaidfees")]
    Networthunpaidfees,
    #[serde(rename = "huntingskill")]
    Huntingskill,
    #[serde(rename = "searchforcashskill")]
    Searchforcashskill,
    #[serde(rename = "bootleggingskill")]
    Bootleggingskill,
    #[serde(rename = "graffitiskill")]
    Graffitiskill,
    #[serde(rename = "shopliftingskill")]
    Shopliftingskill,
    #[serde(rename = "pickpocketingskill")]
    Pickpocketingskill,
    #[serde(rename = "cardskimmingskill")]
    Cardskimmingskill,
    #[serde(rename = "burglaryskill")]
    Burglaryskill,
    #[serde(rename = "hustlingskill")]
    Hustlingskill,
    #[serde(rename = "disposalskill")]
    Disposalskill,
    #[serde(rename = "crackingskill")]
    Crackingskill,
    #[serde(rename = "forgeryskill")]
    Forgeryskill,
    #[serde(rename = "scammingskill")]
    Scammingskill,

}

impl std::fmt::Display for PersonalStatsStatName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Attackswon => write!(f, "attackswon"),
            Self::Attackslost => write!(f, "attackslost"),
            Self::Attacksdraw => write!(f, "attacksdraw"),
            Self::Attacksassisted => write!(f, "attacksassisted"),
            Self::Defendswon => write!(f, "defendswon"),
            Self::Defendslost => write!(f, "defendslost"),
            Self::Defendsstalemated => write!(f, "defendsstalemated"),
            Self::Elo => write!(f, "elo"),
            Self::Yourunaway => write!(f, "yourunaway"),
            Self::Theyrunaway => write!(f, "theyrunaway"),
            Self::Unarmoredwon => write!(f, "unarmoredwon"),
            Self::Bestkillstreak => write!(f, "bestkillstreak"),
            Self::Attackhits => write!(f, "attackhits"),
            Self::Attackmisses => write!(f, "attackmisses"),
            Self::Attackdamage => write!(f, "attackdamage"),
            Self::Bestdamage => write!(f, "bestdamage"),
            Self::Onehitkills => write!(f, "onehitkills"),
            Self::Attackcriticalhits => write!(f, "attackcriticalhits"),
            Self::Roundsfired => write!(f, "roundsfired"),
            Self::Specialammoused => write!(f, "specialammoused"),
            Self::Hollowammoused => write!(f, "hollowammoused"),
            Self::Tracerammoused => write!(f, "tracerammoused"),
            Self::Piercingammoused => write!(f, "piercingammoused"),
            Self::Incendiaryammoused => write!(f, "incendiaryammoused"),
            Self::Attacksstealthed => write!(f, "attacksstealthed"),
            Self::Retals => write!(f, "retals"),
            Self::Moneymugged => write!(f, "moneymugged"),
            Self::Largestmug => write!(f, "largestmug"),
            Self::Itemslooted => write!(f, "itemslooted"),
            Self::Highestbeaten => write!(f, "highestbeaten"),
            Self::Respectforfaction => write!(f, "respectforfaction"),
            Self::Rankedwarhits => write!(f, "rankedwarhits"),
            Self::Raidhits => write!(f, "raidhits"),
            Self::Territoryjoins => write!(f, "territoryjoins"),
            Self::Territoryclears => write!(f, "territoryclears"),
            Self::Territorytime => write!(f, "territorytime"),
            Self::Jobpointsused => write!(f, "jobpointsused"),
            Self::Trainsreceived => write!(f, "trainsreceived"),
            Self::Marketitemsbought => write!(f, "marketitemsbought"),
            Self::Auctionswon => write!(f, "auctionswon"),
            Self::Auctionsells => write!(f, "auctionsells"),
            Self::Itemssent => write!(f, "itemssent"),
            Self::Trades => write!(f, "trades"),
            Self::Cityitemsbought => write!(f, "cityitemsbought"),
            Self::Pointsbought => write!(f, "pointsbought"),
            Self::Pointssold => write!(f, "pointssold"),
            Self::Bazaarcustomers => write!(f, "bazaarcustomers"),
            Self::Bazaarsales => write!(f, "bazaarsales"),
            Self::Bazaarprofit => write!(f, "bazaarprofit"),
            Self::Jailed => write!(f, "jailed"),
            Self::Peoplebusted => write!(f, "peoplebusted"),
            Self::Failedbusts => write!(f, "failedbusts"),
            Self::Peoplebought => write!(f, "peoplebought"),
            Self::Peopleboughtspent => write!(f, "peopleboughtspent"),
            Self::Hospital => write!(f, "hospital"),
            Self::Medicalitemsused => write!(f, "medicalitemsused"),
            Self::Bloodwithdrawn => write!(f, "bloodwithdrawn"),
            Self::Reviveskill => write!(f, "reviveskill"),
            Self::Revives => write!(f, "revives"),
            Self::Revivesreceived => write!(f, "revivesreceived"),
            Self::Heavyhits => write!(f, "heavyhits"),
            Self::Machinehits => write!(f, "machinehits"),
            Self::Riflehits => write!(f, "riflehits"),
            Self::Smghits => write!(f, "smghits"),
            Self::Shotgunhits => write!(f, "shotgunhits"),
            Self::Pistolhits => write!(f, "pistolhits"),
            Self::Temphits => write!(f, "temphits"),
            Self::Piercinghits => write!(f, "piercinghits"),
            Self::Slashinghits => write!(f, "slashinghits"),
            Self::Clubbinghits => write!(f, "clubbinghits"),
            Self::Mechanicalhits => write!(f, "mechanicalhits"),
            Self::H2hhits => write!(f, "h2hhits"),
            Self::Mailssent => write!(f, "mailssent"),
            Self::Friendmailssent => write!(f, "friendmailssent"),
            Self::Factionmailssent => write!(f, "factionmailssent"),
            Self::Companymailssent => write!(f, "companymailssent"),
            Self::Spousemailssent => write!(f, "spousemailssent"),
            Self::Classifiedadsplaced => write!(f, "classifiedadsplaced"),
            Self::Personalsplaced => write!(f, "personalsplaced"),
            Self::Criminaloffensesold => write!(f, "criminaloffensesold"),
            Self::Sellillegalgoods => write!(f, "sellillegalgoods"),
            Self::Theftold => write!(f, "theftold"),
            Self::Autotheftcrime => write!(f, "autotheftcrime"),
            Self::Drugdealscrime => write!(f, "drugdealscrime"),
            Self::Computercrime => write!(f, "computercrime"),
            Self::Fraudold => write!(f, "fraudold"),
            Self::Murdercrime => write!(f, "murdercrime"),
            Self::Othercrime => write!(f, "othercrime"),
            Self::Organizedcrimes => write!(f, "organizedcrimes"),
            Self::Bountiesplaced => write!(f, "bountiesplaced"),
            Self::Totalbountyspent => write!(f, "totalbountyspent"),
            Self::Bountiescollected => write!(f, "bountiescollected"),
            Self::Totalbountyreward => write!(f, "totalbountyreward"),
            Self::Bountiesreceived => write!(f, "bountiesreceived"),
            Self::Receivedbountyvalue => write!(f, "receivedbountyvalue"),
            Self::Cityfinds => write!(f, "cityfinds"),
            Self::Dumpfinds => write!(f, "dumpfinds"),
            Self::Itemsdumped => write!(f, "itemsdumped"),
            Self::Booksread => write!(f, "booksread"),
            Self::Boostersused => write!(f, "boostersused"),
            Self::Consumablesused => write!(f, "consumablesused"),
            Self::Candyused => write!(f, "candyused"),
            Self::Alcoholused => write!(f, "alcoholused"),
            Self::Energydrinkused => write!(f, "energydrinkused"),
            Self::Statenhancersused => write!(f, "statenhancersused"),
            Self::Eastereggsfound => write!(f, "eastereggsfound"),
            Self::Eastereggsused => write!(f, "eastereggsused"),
            Self::Virusescoded => write!(f, "virusescoded"),
            Self::Traveltimes => write!(f, "traveltimes"),
            Self::Timespenttraveling => write!(f, "timespenttraveling"),
            Self::Itemsboughtabroad => write!(f, "itemsboughtabroad"),
            Self::Hunting => write!(f, "hunting"),
            Self::Attackswonabroad => write!(f, "attackswonabroad"),
            Self::Defendslostabroad => write!(f, "defendslostabroad"),
            Self::Argtravel => write!(f, "argtravel"),
            Self::Mextravel => write!(f, "mextravel"),
            Self::Uaetravel => write!(f, "uaetravel"),
            Self::Hawtravel => write!(f, "hawtravel"),
            Self::Japtravel => write!(f, "japtravel"),
            Self::Uktravel => write!(f, "uktravel"),
            Self::Satravel => write!(f, "satravel"),
            Self::Switravel => write!(f, "switravel"),
            Self::Chitravel => write!(f, "chitravel"),
            Self::Cantravel => write!(f, "cantravel"),
            Self::Caytravel => write!(f, "caytravel"),
            Self::Drugsused => write!(f, "drugsused"),
            Self::Overdosed => write!(f, "overdosed"),
            Self::Rehabs => write!(f, "rehabs"),
            Self::Rehabcost => write!(f, "rehabcost"),
            Self::Cantaken => write!(f, "cantaken"),
            Self::Exttaken => write!(f, "exttaken"),
            Self::Kettaken => write!(f, "kettaken"),
            Self::Lsdtaken => write!(f, "lsdtaken"),
            Self::Opitaken => write!(f, "opitaken"),
            Self::Pcptaken => write!(f, "pcptaken"),
            Self::Shrtaken => write!(f, "shrtaken"),
            Self::Spetaken => write!(f, "spetaken"),
            Self::Victaken => write!(f, "victaken"),
            Self::Xantaken => write!(f, "xantaken"),
            Self::Missionscompleted => write!(f, "missionscompleted"),
            Self::Contractscompleted => write!(f, "contractscompleted"),
            Self::Dukecontractscompleted => write!(f, "dukecontractscompleted"),
            Self::Missioncreditsearned => write!(f, "missioncreditsearned"),
            Self::Racingskill => write!(f, "racingskill"),
            Self::Racingpointsearned => write!(f, "racingpointsearned"),
            Self::Racesentered => write!(f, "racesentered"),
            Self::Raceswon => write!(f, "raceswon"),
            Self::Networth => write!(f, "networth"),
            Self::Timeplayed => write!(f, "timeplayed"),
            Self::Activestreak => write!(f, "activestreak"),
            Self::Bestactivestreak => write!(f, "bestactivestreak"),
            Self::Awards => write!(f, "awards"),
            Self::Refills => write!(f, "refills"),
            Self::Nerverefills => write!(f, "nerverefills"),
            Self::Tokenrefills => write!(f, "tokenrefills"),
            Self::Meritsbought => write!(f, "meritsbought"),
            Self::Daysbeendonator => write!(f, "daysbeendonator"),
            Self::Criminaloffenses => write!(f, "criminaloffenses"),
            Self::Vandalism => write!(f, "vandalism"),
            Self::Theft => write!(f, "theft"),
            Self::Counterfeiting => write!(f, "counterfeiting"),
            Self::Fraud => write!(f, "fraud"),
            Self::Illicitservices => write!(f, "illicitservices"),
            Self::Cybercrime => write!(f, "cybercrime"),
            Self::Extortion => write!(f, "extortion"),
            Self::Illegalproduction => write!(f, "illegalproduction"),
            Self::Currentkillstreak => write!(f, "currentkillstreak"),
            Self::Strength => write!(f, "strength"),
            Self::Defense => write!(f, "defense"),
            Self::Speed => write!(f, "speed"),
            Self::Dexterity => write!(f, "dexterity"),
            Self::Totalstats => write!(f, "totalstats"),
            Self::Manuallabor => write!(f, "manuallabor"),
            Self::Intelligence => write!(f, "intelligence"),
            Self::Endurance => write!(f, "endurance"),
            Self::Totalworkingstats => write!(f, "totalworkingstats"),
            Self::Moneyinvested => write!(f, "moneyinvested"),
            Self::Investedprofit => write!(f, "investedprofit"),
            Self::Investamount => write!(f, "investamount"),
            Self::Banktimeleft => write!(f, "banktimeleft"),
            Self::Stockprofits => write!(f, "stockprofits"),
            Self::Stocklosses => write!(f, "stocklosses"),
            Self::Stockfees => write!(f, "stockfees"),
            Self::Stocknetprofits => write!(f, "stocknetprofits"),
            Self::Stockpayouts => write!(f, "stockpayouts"),
            Self::Networthwallet => write!(f, "networthwallet"),
            Self::Networthvault => write!(f, "networthvault"),
            Self::Networthbank => write!(f, "networthbank"),
            Self::Networthcayman => write!(f, "networthcayman"),
            Self::Networthpoints => write!(f, "networthpoints"),
            Self::Networthitems => write!(f, "networthitems"),
            Self::Networthdisplaycase => write!(f, "networthdisplaycase"),
            Self::Networthbazaar => write!(f, "networthbazaar"),
            Self::Networthitemmarket => write!(f, "networthitemmarket"),
            Self::Networthproperties => write!(f, "networthproperties"),
            Self::Networthstockmarket => write!(f, "networthstockmarket"),
            Self::Networthauctionhouse => write!(f, "networthauctionhouse"),
            Self::Networthbookie => write!(f, "networthbookie"),
            Self::Networthcompany => write!(f, "networthcompany"),
            Self::Networthenlistedcars => write!(f, "networthenlistedcars"),
            Self::Networthpiggybank => write!(f, "networthpiggybank"),
            Self::Networthpending => write!(f, "networthpending"),
            Self::Networthloan => write!(f, "networthloan"),
            Self::Networthunpaidfees => write!(f, "networthunpaidfees"),
            Self::Huntingskill => write!(f, "huntingskill"),
            Self::Searchforcashskill => write!(f, "searchforcashskill"),
            Self::Bootleggingskill => write!(f, "bootleggingskill"),
            Self::Graffitiskill => write!(f, "graffitiskill"),
            Self::Shopliftingskill => write!(f, "shopliftingskill"),
            Self::Pickpocketingskill => write!(f, "pickpocketingskill"),
            Self::Cardskimmingskill => write!(f, "cardskimmingskill"),
            Self::Burglaryskill => write!(f, "burglaryskill"),
            Self::Hustlingskill => write!(f, "hustlingskill"),
            Self::Disposalskill => write!(f, "disposalskill"),
            Self::Crackingskill => write!(f, "crackingskill"),
            Self::Forgeryskill => write!(f, "forgeryskill"),
            Self::Scammingskill => write!(f, "scammingskill"),
        }
    }
}

impl Default for PersonalStatsStatName {
    fn default() -> PersonalStatsStatName {
        Self::Attackswon
    }
}

