/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsDrugsDrugs {
    #[serde(rename = "cannabis", skip_serializing_if = "Option::is_none")]
    pub cannabis: Option<i32>,
    #[serde(rename = "ecstasy", skip_serializing_if = "Option::is_none")]
    pub ecstasy: Option<i32>,
    #[serde(rename = "ketamine", skip_serializing_if = "Option::is_none")]
    pub ketamine: Option<i32>,
    #[serde(rename = "lsd", skip_serializing_if = "Option::is_none")]
    pub lsd: Option<i32>,
    #[serde(rename = "opium", skip_serializing_if = "Option::is_none")]
    pub opium: Option<i32>,
    #[serde(rename = "pcp", skip_serializing_if = "Option::is_none")]
    pub pcp: Option<i32>,
    #[serde(rename = "shrooms", skip_serializing_if = "Option::is_none")]
    pub shrooms: Option<i32>,
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<i32>,
    #[serde(rename = "vicodin", skip_serializing_if = "Option::is_none")]
    pub vicodin: Option<i32>,
    #[serde(rename = "xanax", skip_serializing_if = "Option::is_none")]
    pub xanax: Option<i32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "overdoses", skip_serializing_if = "Option::is_none")]
    pub overdoses: Option<i32>,
    #[serde(rename = "rehabilitations", skip_serializing_if = "Option::is_none")]
    pub rehabilitations: Option<Box<models::PersonalStatsDrugsDrugsRehabilitations>>,
}

impl PersonalStatsDrugsDrugs {
    pub fn new() -> PersonalStatsDrugsDrugs {
        PersonalStatsDrugsDrugs {
            cannabis: None,
            ecstasy: None,
            ketamine: None,
            lsd: None,
            opium: None,
            pcp: None,
            shrooms: None,
            speed: None,
            vicodin: None,
            xanax: None,
            total: None,
            overdoses: None,
            rehabilitations: None,
        }
    }
}

