/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsJailJail {
    #[serde(rename = "times_jailed", skip_serializing_if = "Option::is_none")]
    pub times_jailed: Option<i32>,
    #[serde(rename = "busts", skip_serializing_if = "Option::is_none")]
    pub busts: Option<Box<models::PersonalStatsJailJailBusts>>,
    #[serde(rename = "bails", skip_serializing_if = "Option::is_none")]
    pub bails: Option<Box<models::PersonalStatsDrugsDrugsRehabilitations>>,
}

impl PersonalStatsJailJail {
    pub fn new() -> PersonalStatsJailJail {
        PersonalStatsJailJail {
            times_jailed: None,
            busts: None,
            bails: None,
        }
    }
}

