/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalStatsJobsExtendedJobs {
    #[serde(rename = "job_points_used", skip_serializing_if = "Option::is_none")]
    pub job_points_used: Option<i32>,
    #[serde(rename = "trains_received", skip_serializing_if = "Option::is_none")]
    pub trains_received: Option<i32>,
    #[serde(rename = "stats", skip_serializing_if = "Option::is_none")]
    pub stats: Option<Box<models::PersonalStatsJobsExtendedJobsStats>>,
}

impl PersonalStatsJobsExtendedJobs {
    pub fn new() -> PersonalStatsJobsExtendedJobs {
        PersonalStatsJobsExtendedJobs {
            job_points_used: None,
            trains_received: None,
            stats: None,
        }
    }
}

