/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RaceRecord {
    #[serde(rename = "driver_id", skip_serializing_if = "Option::is_none")]
    pub driver_id: Option<i32>,
    #[serde(rename = "driver_name", skip_serializing_if = "Option::is_none")]
    pub driver_name: Option<String>,
    #[serde(rename = "car_item_id", skip_serializing_if = "Option::is_none")]
    pub car_item_id: Option<i32>,
    #[serde(rename = "lap_time", skip_serializing_if = "Option::is_none")]
    pub lap_time: Option<i32>,
    #[serde(rename = "car_item_name", skip_serializing_if = "Option::is_none")]
    pub car_item_name: Option<String>,
}

impl RaceRecord {
    pub fn new() -> RaceRecord {
        RaceRecord {
            driver_id: None,
            driver_name: None,
            car_item_id: None,
            lap_time: None,
            car_item_name: None,
        }
    }
}

