/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestLinks {
    /// Auto-generated link to get the next set of records.
    #[serde(rename = "next", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next: Option<Option<String>>,
    /// Auto-generated link to get the prev set of records.
    #[serde(rename = "prev", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub prev: Option<Option<String>>,
}

impl RequestLinks {
    pub fn new() -> RequestLinks {
        RequestLinks {
            next: None,
            prev: None,
        }
    }
}

