/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserCrimeDetailsBootleggingDvdSales : DVD sales statistics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCrimeDetailsBootleggingDvdSales {
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<i32>,
    #[serde(rename = "comedy", skip_serializing_if = "Option::is_none")]
    pub comedy: Option<i32>,
    #[serde(rename = "drama", skip_serializing_if = "Option::is_none")]
    pub drama: Option<i32>,
    #[serde(rename = "fantasy", skip_serializing_if = "Option::is_none")]
    pub fantasy: Option<i32>,
    #[serde(rename = "horror", skip_serializing_if = "Option::is_none")]
    pub horror: Option<i32>,
    #[serde(rename = "romance", skip_serializing_if = "Option::is_none")]
    pub romance: Option<i32>,
    #[serde(rename = "thriller", skip_serializing_if = "Option::is_none")]
    pub thriller: Option<i32>,
    #[serde(rename = "sci-fi", skip_serializing_if = "Option::is_none")]
    pub sci_fi: Option<i32>,
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "earnings", skip_serializing_if = "Option::is_none")]
    pub earnings: Option<i32>,
}

impl UserCrimeDetailsBootleggingDvdSales {
    /// DVD sales statistics.
    pub fn new() -> UserCrimeDetailsBootleggingDvdSales {
        UserCrimeDetailsBootleggingDvdSales {
            action: None,
            comedy: None,
            drama: None,
            fantasy: None,
            horror: None,
            romance: None,
            thriller: None,
            sci_fi: None,
            total: None,
            earnings: None,
        }
    }
}

