/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UserPersonalStatsCategoryPersonalstats {
    PersonalStatsAttackingPublic(Box<models::PersonalStatsAttackingPublic>),
    PersonalStatsJobsPublic(Box<models::PersonalStatsJobsPublic>),
    PersonalStatsTrading(Box<models::PersonalStatsTrading>),
    PersonalStatsJail(Box<models::PersonalStatsJail>),
    PersonalStatsHospital(Box<models::PersonalStatsHospital>),
    PersonalStatsFinishingHits(Box<models::PersonalStatsFinishingHits>),
    PersonalStatsCommunication(Box<models::PersonalStatsCommunication>),
    PersonalStatsCriminalOffenses(Box<models::PersonalStatsCriminalOffenses>),
    PersonalStatsCrimes(Box<models::PersonalStatsCrimes>),
    PersonalStatsBounties(Box<models::PersonalStatsBounties>),
    PersonalStatsItems(Box<models::PersonalStatsItems>),
    PersonalStatsTravel(Box<models::PersonalStatsTravel>),
    PersonalStatsDrugs(Box<models::PersonalStatsDrugs>),
    PersonalStatsMissions(Box<models::PersonalStatsMissions>),
    PersonalStatsRacing(Box<models::PersonalStatsRacing>),
    PersonalStatsNetworthPublic(Box<models::PersonalStatsNetworthPublic>),
    PersonalStatsOther(Box<models::PersonalStatsOther>),
}

impl Default for UserPersonalStatsCategoryPersonalstats {
    fn default() -> Self {
        Self::PersonalStatsAttackingPublic(Default::default())
    }
}

