/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSelectionName : The following selections will fallback to API v1 and may change at any time: 'ammo','attacks','attacksfull','bars','basic','battlestats','bazaar','cooldowns','criminalrecord','discord','display','education','equipment','events','gym','honors','icons','inventory','jobpoints','log','medals','merits','messages','missions','money','networth','newevents','newmessages','notifications','perks','profile','properties','refills','reports','revives','revivesfull','skills','stocks','travel','weaponexp','workstats'.
/// The following selections will fallback to API v1 and may change at any time: 'ammo','attacks','attacksfull','bars','basic','battlestats','bazaar','cooldowns','criminalrecord','discord','display','education','equipment','events','gym','honors','icons','inventory','jobpoints','log','medals','merits','messages','missions','money','networth','newevents','newmessages','notifications','perks','profile','properties','refills','reports','revives','revivesfull','skills','stocks','travel','weaponexp','workstats'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserSelectionName {
    #[serde(rename = "bounties")]
    Bounties,
    #[serde(rename = "calendar")]
    Calendar,
    #[serde(rename = "crimes")]
    Crimes,
    #[serde(rename = "enlistedcars")]
    Enlistedcars,
    #[serde(rename = "forumfeed")]
    Forumfeed,
    #[serde(rename = "forumfriends")]
    Forumfriends,
    #[serde(rename = "forumposts")]
    Forumposts,
    #[serde(rename = "forumsubscribedthreads")]
    Forumsubscribedthreads,
    #[serde(rename = "forumthreads")]
    Forumthreads,
    #[serde(rename = "hof")]
    Hof,
    #[serde(rename = "itemmarket")]
    Itemmarket,
    #[serde(rename = "jobranks")]
    Jobranks,
    #[serde(rename = "lookup")]
    Lookup,
    #[serde(rename = "personalstats")]
    Personalstats,
    #[serde(rename = "races")]
    Races,
    #[serde(rename = "timestamp")]
    Timestamp,
    #[serde(rename = "ammo")]
    Ammo,
    #[serde(rename = "attacks")]
    Attacks,
    #[serde(rename = "attacksfull")]
    Attacksfull,
    #[serde(rename = "bars")]
    Bars,
    #[serde(rename = "basic")]
    Basic,
    #[serde(rename = "battlestats")]
    Battlestats,
    #[serde(rename = "bazaar")]
    Bazaar,
    #[serde(rename = "cooldowns")]
    Cooldowns,
    #[serde(rename = "criminalrecord")]
    Criminalrecord,
    #[serde(rename = "discord")]
    Discord,
    #[serde(rename = "display")]
    Display,
    #[serde(rename = "education")]
    Education,
    #[serde(rename = "equipment")]
    Equipment,
    #[serde(rename = "events")]
    Events,
    #[serde(rename = "gym")]
    Gym,
    #[serde(rename = "honors")]
    Honors,
    #[serde(rename = "icons")]
    Icons,
    #[serde(rename = "inventory")]
    Inventory,
    #[serde(rename = "jobpoints")]
    Jobpoints,
    #[serde(rename = "log")]
    Log,
    #[serde(rename = "medals")]
    Medals,
    #[serde(rename = "merits")]
    Merits,
    #[serde(rename = "messages")]
    Messages,
    #[serde(rename = "missions")]
    Missions,
    #[serde(rename = "money")]
    Money,
    #[serde(rename = "networth")]
    Networth,
    #[serde(rename = "newevents")]
    Newevents,
    #[serde(rename = "newmessages")]
    Newmessages,
    #[serde(rename = "notifications")]
    Notifications,
    #[serde(rename = "perks")]
    Perks,
    #[serde(rename = "profile")]
    Profile,
    #[serde(rename = "properties")]
    Properties,
    #[serde(rename = "refills")]
    Refills,
    #[serde(rename = "reports")]
    Reports,
    #[serde(rename = "revives")]
    Revives,
    #[serde(rename = "revivesfull")]
    Revivesfull,
    #[serde(rename = "skills")]
    Skills,
    #[serde(rename = "stocks")]
    Stocks,
    #[serde(rename = "travel")]
    Travel,
    #[serde(rename = "weaponexp")]
    Weaponexp,
    #[serde(rename = "workstats")]
    Workstats,

}

impl std::fmt::Display for UserSelectionName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bounties => write!(f, "bounties"),
            Self::Calendar => write!(f, "calendar"),
            Self::Crimes => write!(f, "crimes"),
            Self::Enlistedcars => write!(f, "enlistedcars"),
            Self::Forumfeed => write!(f, "forumfeed"),
            Self::Forumfriends => write!(f, "forumfriends"),
            Self::Forumposts => write!(f, "forumposts"),
            Self::Forumsubscribedthreads => write!(f, "forumsubscribedthreads"),
            Self::Forumthreads => write!(f, "forumthreads"),
            Self::Hof => write!(f, "hof"),
            Self::Itemmarket => write!(f, "itemmarket"),
            Self::Jobranks => write!(f, "jobranks"),
            Self::Lookup => write!(f, "lookup"),
            Self::Personalstats => write!(f, "personalstats"),
            Self::Races => write!(f, "races"),
            Self::Timestamp => write!(f, "timestamp"),
            Self::Ammo => write!(f, "ammo"),
            Self::Attacks => write!(f, "attacks"),
            Self::Attacksfull => write!(f, "attacksfull"),
            Self::Bars => write!(f, "bars"),
            Self::Basic => write!(f, "basic"),
            Self::Battlestats => write!(f, "battlestats"),
            Self::Bazaar => write!(f, "bazaar"),
            Self::Cooldowns => write!(f, "cooldowns"),
            Self::Criminalrecord => write!(f, "criminalrecord"),
            Self::Discord => write!(f, "discord"),
            Self::Display => write!(f, "display"),
            Self::Education => write!(f, "education"),
            Self::Equipment => write!(f, "equipment"),
            Self::Events => write!(f, "events"),
            Self::Gym => write!(f, "gym"),
            Self::Honors => write!(f, "honors"),
            Self::Icons => write!(f, "icons"),
            Self::Inventory => write!(f, "inventory"),
            Self::Jobpoints => write!(f, "jobpoints"),
            Self::Log => write!(f, "log"),
            Self::Medals => write!(f, "medals"),
            Self::Merits => write!(f, "merits"),
            Self::Messages => write!(f, "messages"),
            Self::Missions => write!(f, "missions"),
            Self::Money => write!(f, "money"),
            Self::Networth => write!(f, "networth"),
            Self::Newevents => write!(f, "newevents"),
            Self::Newmessages => write!(f, "newmessages"),
            Self::Notifications => write!(f, "notifications"),
            Self::Perks => write!(f, "perks"),
            Self::Profile => write!(f, "profile"),
            Self::Properties => write!(f, "properties"),
            Self::Refills => write!(f, "refills"),
            Self::Reports => write!(f, "reports"),
            Self::Revives => write!(f, "revives"),
            Self::Revivesfull => write!(f, "revivesfull"),
            Self::Skills => write!(f, "skills"),
            Self::Stocks => write!(f, "stocks"),
            Self::Travel => write!(f, "travel"),
            Self::Weaponexp => write!(f, "weaponexp"),
            Self::Workstats => write!(f, "workstats"),
        }
    }
}

impl Default for UserSelectionName {
    fn default() -> UserSelectionName {
        Self::Bounties
    }
}

