/*
 * Torn API
 *
 *   * The development of Torn's API v2 is still ongoing.  * If selections remain unaltered, they will default to the API v1 version.  * Unlike API v1, API v2 accepts both selections and IDs as path and query parameters.  * If any discrepancies or errors are found, please submit a [bug report](https://www.torn.com/forums.php#/p=forums&f=19&b=0&a=0) on the Torn Forums.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCrimeDetailsBootlegging {
    #[serde(rename = "online_store", skip_serializing_if = "Option::is_none")]
    pub online_store: Option<Box<models::UserCrimeDetailsBootleggingOnlineStore>>,
    #[serde(rename = "dvd_sales", skip_serializing_if = "Option::is_none")]
    pub dvd_sales: Option<Box<models::UserCrimeDetailsBootleggingDvdSales>>,
    #[serde(rename = "dvds_copied", skip_serializing_if = "Option::is_none")]
    pub dvds_copied: Option<i32>,
}

impl UserCrimeDetailsBootlegging {
    pub fn new() -> UserCrimeDetailsBootlegging {
        UserCrimeDetailsBootlegging {
            online_store: None,
            dvd_sales: None,
            dvds_copied: None,
        }
    }
}

